services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.12.3
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./etc/clickhouse-server:/etc/clickhouse-server
      - ./etc/clickhouse-keeper:/etc/clickhouse-keeper
      - ./etc/clickhouse-client:/etc/clickhouse-client
      - ./data:/var/lib/clickhouse
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE